version: "3.7"

services:
  broker:
    image: rabbitmq
    expose:
      - "5672"
    ports:
      - 5672:5672

  worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile.worker
    volumes:
      - .:/django_celery/
    command: sh bin/celery-start
    depends_on:
      - broker

  flower:
    image: mher/flower
    volumes:
      - .:/django_celery/
    command: sh bin/flower-start
    depends_on:
      - worker
    expose:
      - "5555"
    ports:
      - 5555:5555

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/django_celery/
    command: sh bin/django-start
    depends_on:
      - broker
      - worker
    expose:
      - "8000"
    ports:
      - 8000:8000
