version: "3.8"

services:
  broker:
    image: redis:buster
    volumes:
      - ./django_app/logs/broker/:/var/log/redis/
    restart: always
    expose:
      - "6379"
    ports:
      - 6379:6379
    networks:
      - net
  # broker:
  #   image: rabbitmq
  # volumes:
  #   - ./logs/broker/:/var/log/redis/
  #   restart: always
  # expose:
  #   - "5276"
  #   ports:
  #     - 5672:5672
  #   # networks:
  #   #   - net

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    hostname: myhost
    working_dir: /django_celery/
    volumes:
      - ./django_app/:/django_celery/
      - ./django_app/static/:/django_celery/static/
      - ./django_app/media/:/django_celery/media/
      - ./django_app/logs/:/django_celery/logs/
      - ./django_app/ssl/:/django_celery/ssl/
    depends_on:
      - broker
    restart: on-failure
    ports:
      - 8000:8000
    networks:
      - net

  # flower:
  #   image: mher/flower:0.9.4
  #   environment:
  #     - CELERY_BROKER_URL=redis://broker:6379
  #     - FLOWER_PORT=5555
  #   depends_on:
  #     - broker
  #     - django
  #   restart: always
  #   ports:
  #     - 5555:5555
  #   networks:
  #     - net

  nginx:
    image: nginx:mainline-alpine
    working_dir: /django_celery/
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./django_app/logs/nginx/:/var/log/nginx/
      - ./django_app/static/:/django_celery/static/
      - ./django_app/media/:/django_celery/media/
      - ./django_app/ssl/:/django_celery/ssl/
    depends_on:
      - django
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - net

networks:
  net:
    driver: bridge
