version: "3.8"

services:
  broker:
    image: rabbitmq
    expose:
      - "5672"
    ports:
      - 5672:5672
    networks:
      - net

  worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    volumes:
      - .:/django_celery/
    command: sh bin/celery-start
    depends_on:
      - broker
    networks:
      - net

  flower:
    image: mher/flower
    volumes:
      - .:/django_celery/
    command: sh bin/flower-start
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker:5672
      # - CELERY_BROKER_URL=amqp://guest:guest@localhost:5672
      - FLOWER_PORT=5555
      # - FLOWER_URL_PREFIX=flower
    depends_on:
      - broker
    expose:
      - "5555"
    ports:
      - 5555:5555
    networks:
      - net

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - .:/django_celery/
      # - ./static/:/django_celery/static/
      # - ./media/:/django_celery/media/
    command: sh bin/django-start
    depends_on:
      - worker
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  django_celery:
networks:
  net:
