version: "3.8"

services:
  manager:
    image: portainer/portainer-ce:latest
    # image: portainer/portainer-ce:alpine for raspberry version
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    expose:
      - "9000"
    ports:
      - 9000:9000
    networks:
      - app_net

  broker:
    # image: redis:buster
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    hostname: broker
    volumes:
      - ./docker/redis/redis.conf/:/usr/local/etc/redis/redis.conf
      - ./django_app/logs/broker/:/var/log/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    expose:
      - "6379"
    ports:
      - 6379:6379
    networks:
      - app_net

  django:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
      args:
        - APP_TITLE=${APP_TITLE}
        - DEBUG=${DEBUG}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - DJANGO_PORT=${DJANGO_PORT}
        - SECRET_KEY=${SECRET_KEY}
    hostname: django
    working_dir: /django_celery/
    volumes:
      - ./django_app/:/django_celery/
      - ./django_app/static/:/django_celery/static/
      - ./django_app/media/:/django_celery/media/
      - ./django_app/logs/:/django_celery/logs/
      - ./django_app/ssl/:/django_celery/ssl/
    command: sh bin/django-start
    env_file: .env
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000
    networks:
      - app_net

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    hostname: worker
    working_dir: /django_celery/
    volumes_from:
      - django
    command: sh bin/celery-worker-start
    depends_on:
      - broker
      - django
    restart: always
    networks:
      - app_net

  beat:
    build:
      context: .
      dockerfile: docker/beat/Dockerfile
    hostname: beat
    working_dir: /django_celery/
    volumes_from:
      - django
    command: sh bin/celery-beat-start
    depends_on:
      - broker
      - django
    restart: always
    networks:
      - app_net

  flower:
    image: mher/flower:0.9.4
    hostname: flower
    environment:
      - CELERY_BROKER_URL=redis://broker:6379
      - FLOWER_PORT=5555
      - FLOWEE_PREFIX=/flower/
    depends_on:
      - broker
    restart: always
    ports:
      - 5555:5555
    networks:
      - app_net

  nginx:
    image: nginx:mainline-alpine
    hostname: nginx
    working_dir: /django_celery/
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./django_app/logs/nginx/:/var/log/nginx/
      - ./django_app/static/:/django_celery/static/
      - ./django_app/media/:/django_celery/media/
      - ./django_app/ssl/:/django_celery/ssl/
    depends_on:
      - django
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - app_net

networks:
  app_net:
