version: "3.8"

services:
  broker:
    image: rabbitmq
    expose:
      - "5672"
    ports:
      - 5672:5672

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/django_celery/
    command: sh bin/celery-start
    depends_on:
      - broker

  flower:
    image: mher/flower
    volumes:
      - .:/django_celery/
    command: sh bin/flower-start
    environment:
      - CELERY_BROKER_URL=amqp://broker:5672
      - FLOWER_PORT=5555
      - FLOWER_URL_PREFIX=flower
    depends_on:
      - worker
    expose:
      - "5555"
    ports:
      - 5555:5555

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - .:/django_celery/
    command: sh bin/django-start
    depends_on:
      - broker
      - worker
    expose:
      - "8000"
    ports:
      - 8000:8000
volumes:
  django_celery:
