#!/bin/bash
# The script configures device for using greenponik
# Distribution Raspbian Buster
# works on:
#           -Raspberry Pi Zero W
#           -Raspberry Pi 3 B+
#           -Raspberry Pi 3 A+
# Licence: no licence private script copyright greenponik sas
# Author: Mickael Lehoux <mickael.lehoux@greenponik.com>

set -x

# test if docker rabbitmq container broker exist
is_exist=$(docker ps -a | grep -c broker)
if [[ is_exist -eq 0  ]]; then
    # docker run -d -p 5672:5672 --name broker rabbitmq
    # docker run -d -p 6379:6379 --name broker redis:buster
    echo "broker is starting"
    # use docker run command only for tests
    # docker run -d -p 6379:6379 --name broker arm32v7/redis:buster --maxmemory 50Mb --tcp-backlog 128
    # TODO replace by docker-compose command
    docker-compose -f docker-compose.yml -d up broker
else
    docker start broker
fi
sleep 5
if [[ $(docker ps | grep -c broker) ]]; then
    echo "broker started"
else
    echo "there is a probleme to start broker..."
fi
